In [ ]:
import pandas as pd


df1 = pd.read_csv("../dataset/Friday-WorkingHours-Morning.pcap_ISCX.csv")

df2 = pd.read_csv("../dataset/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

df3 = pd.read_csv("../dataset/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")



df4 = pd.read_csv(
    "../dataset/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv",
    encoding="cp1252"
)

df5 = pd.read_csv("../dataset/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")

df6 = pd.read_csv("../dataset/Tuesday-WorkingHours.pcap_ISCX.csv")

df7 = pd.read_csv("../dataset/Wednesday-workingHours.pcap_ISCX.csv")

df = pd.concat([df1, df2, df3, df4,df5,df6,df7], ignore_index=True)

print(df.shape)

In [7]:
df.describe()

c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,191033.000000,191033.000000,191033.000000,1.910330e+05,191033.000000,191033.000000,1.910330e+05,1.910330e+05,191033.000000,191033.000000,...,191033.000000,191033.000000,1.910330e+05,1.910330e+05,1.910330e+05,1.910330e+05,1.910330e+05,1.910330e+05,1.910330e+05,1.910330e+05
mean,38485.431360,6756.069988,11.504756,1.164499e+07,13.826548,16.413714,5.999468e+02,2.838565e+04,174.715803,23.897646,...,10.323735,25.585407,8.596271e+04,5.382912e+04,1.834991e+05,5.589691e+04,3.917041e+06,1.750674e+05,4.048164e+06,3.745754e+06
std,24225.650898,16697.438823,5.507385,3.070084e+07,1097.755533,1479.792387,7.924198e+03,3.314538e+06,554.475223,41.909942,...,1046.038121,6.380665,8.681320e+05,4.929487e+05,1.333719e+06,7.628561e+05,1.388267e+07,2.167443e+06,1.424123e+07,1.370477e+07
min,0.000000,0.000000,0.000000,-1.200000e+01,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5969.000000,53.000000,6.000000,1.940000e+02,2.000000,1.000000,4.000000e+01,6.000000e+00,30.000000,0.000000,...,0.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,50630.000000,80.000000,17.000000,3.112100e+04,2.000000,2.000000,7.000000e+01,1.520000e+02,42.000000,23.000000,...,1.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,58820.000000,443.000000,17.000000,4.102840e+05,4.000000,2.000000,1.520000e+02,3.440000e+02,64.000000,42.000000,...,2.000000,32.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,65535.000000,64948.000000,17.000000,1.200000e+08,207964.000000,284602.000000,1.235152e+06,6.270000e+08,24820.000000,2325.000000,...,198636.000000,56.000000,1.060000e+08,5.040000e+07,1.060000e+08,1.060000e+08,1.200000e+08,7.660000e+07,1.200000e+08,1.200000e+08

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191033 entries, 0 to 191032
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       191033 non-null  object
 1    Source IP                    191033 non-null  object
 2    Source Port                  191033 non-null  int64
 3    Destination IP               191033 non-null  object
 4    Destination Port             191033 non-null  int64
 5    Protocol                     191033 non-null  int64
 6    Timestamp                    191033 non-null  object
 7    Flow Duration                191033 non-null  int64
 8    Total Fwd Packets            191033 non-null  int64
 9    Total Backward Packets       191033 non-null  int64
 10  Total Length of Fwd Packets   191033 non-null  int64
 11   Total Length of Bwd Packets  191033 non-null  float64
 12   Fwd Packet Length Max        191033 non-null  int64
 13   Fwd Packet Length Min        191033 non-null  int64
 14   Fwd Packet Length Mean       191033 non-null  float64
 15   Fwd Packet Length Std        191033 non-null  float64
 16  Bwd Packet Length Max         191033 non-null  int64
 17   Bwd Packet Length Min        191033 non-null  int64
 18   Bwd Packet Length Mean       191033 non-null  float64
 19   Bwd Packet Length Std        191033 non-null  float64
 20  Flow Bytes/s                  191005 non-null  float64
 21   Flow Packets/s               191033 non-null  float64
 22   Flow IAT Mean                191033 non-null  float64
 23   Flow IAT Std                 191033 non-null  float64
 24   Flow IAT Max                 191033 non-null  float64
 25   Flow IAT Min                 191033 non-null  float64
 26  Fwd IAT Total                 191033 non-null  float64
 27   Fwd IAT Mean                 191033 non-null  float64
 28   Fwd IAT Std                  191033 non-null  float64
 29   Fwd IAT Max                  191033 non-null  float64
 30   Fwd IAT Min                  191033 non-null  float64
 31  Bwd IAT Total                 191033 non-null  float64
 32   Bwd IAT Mean                 191033 non-null  float64
 33   Bwd IAT Std                  191033 non-null  float64
 34   Bwd IAT Max                  191033 non-null  float64
 35   Bwd IAT Min                  191033 non-null  float64
 36  Fwd PSH Flags                 191033 non-null  int64
 37   Bwd PSH Flags                191033 non-null  int64
 38   Fwd URG Flags                191033 non-null  int64
 39   Bwd URG Flags                191033 non-null  int64
 40   Fwd Header Length            191033 non-null  int64
 41   Bwd Header Length            191033 non-null  int64
 42  Fwd Packets/s                 191033 non-null  float64
 43   Bwd Packets/s                191033 non-null  float64
 44   Min Packet Length            191033 non-null  int64
 45   Max Packet Length            191033 non-null  int64
 46   Packet Length Mean           191033 non-null  float64
 47   Packet Length Std            191033 non-null  float64
 48   Packet Length Variance       191033 non-null  float64
 49  FIN Flag Count                191033 non-null  int64
 50   SYN Flag Count               191033 non-null  int64
 51   RST Flag Count               191033 non-null  int64
 52   PSH Flag Count               191033 non-null  int64
 53   ACK Flag Count               191033 non-null  int64
 54   URG Flag Count               191033 non-null  int64
 55   CWE Flag Count               191033 non-null  int64
 56   ECE Flag Count               191033 non-null  int64
 57   Down/Up Ratio                191033 non-null  int64
 58   Average Packet Size          191033 non-null  float64
 59   Avg Fwd Segment Size         191033 non-null  float64
 60   Avg Bwd Segment Size         191033 non-null  float64
 61   Fwd Header Length.1          191033 non-null  int64
 62  Fwd Avg Bytes/Bulk            191033 non-null  int64
 63   Fwd Avg Packets/Bulk         191033 non-null  int64
 64   Fwd Avg Bulk Rate            191033 non-null  int64
 65   Bwd Avg Bytes/Bulk           191033 non-null  int64
 66   Bwd Avg Packets/Bulk         191033 non-null  int64
 67  Bwd Avg Bulk Rate             191033 non-null  int64
 68  Subflow Fwd Packets           191033 non-null  int64
 69   Subflow Fwd Bytes            191033 non-null  int64
 70   Subflow Bwd Packets          191033 non-null  int64
 71   Subflow Bwd Bytes            191033 non-null  int64
 72  Init_Win_bytes_forward        191033 non-null  int64
 73   Init_Win_bytes_backward      191033 non-null  int64
 74   act_data_pkt_fwd             191033 non-null  int64
 75   min_seg_size_forward         191033 non-null  int64
 76  Active Mean                   191033 non-null  float64
 77   Active Std                   191033 non-null  float64
 78   Active Max                   191033 non-null  float64
 79   Active Min                   191033 non-null  float64
 80  Idle Mean                     191033 non-null  float64
 81   Idle Std                     191033 non-null  float64
 82   Idle Max                     191033 non-null  float64
 83   Idle Min                     191033 non-null  float64
 84   Label                        191033 non-null  object
dtypes: float64(37), int64(43), object(5)
memory usage: 123.9+ MB

In [10]:
df.shape

(191033, 85)

In [11]:
df.columns

Index(['Flow ID', ' Source IP', ' Source Port', ' Destination IP',
       ' Destination Port', ' Protocol', ' Timestamp', ' Flow Duration',
       ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', ' Label'],
      dtype='object')

In [12]:
df.dtypes

Flow ID               object
 Source IP            object
 Source Port           int64
 Destination IP       object
 Destination Port      int64
                      ...
Idle Mean            float64
 Idle Std            float64
 Idle Max            float64
 Idle Min            float64
 Label                object
Length: 85, dtype: object

In [13]:
df.isnull().sum()

Flow ID              0
 Source IP           0
 Source Port         0
 Destination IP      0
 Destination Port    0
                    ..
Idle Mean            0
 Idle Std            0
 Idle Max            0
 Idle Min            0
 Label               0
Length: 85, dtype: int64

In [14]:
df.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.3-192.168.10.50-3268-56108-6,192.168.10.50,56108,192.168.10.3,3268,6,7/7/2017 8:59,112740690,32,16,...,32,3.594286e+02,1.199802e+01,380.0,343.0,16100000.0,4.988048e+05,16400000.0,15400000.0,BENIGN
1,192.168.10.3-192.168.10.50-389-42144-6,192.168.10.50,42144,192.168.10.3,389,6,7/7/2017 8:59,112740560,32,16,...,32,3.202857e+02,1.574499e+01,330.0,285.0,16100000.0,4.987937e+05,16400000.0,15400000.0,BENIGN
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,7/7/2017 9:00,113757377,545,0,...,0,9.361829e+06,7.324646e+06,18900000.0,19.0,12200000.0,6.935824e+06,20800000.0,5504997.0,BENIGN
3,192.168.10.9-224.0.0.252-63210-5355-17,192.168.10.9,63210,224.0.0.252,5355,17,7/7/2017 9:00,100126,22,0,...,32,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,BENIGN
4,192.168.10.9-224.0.0.22-0-0-0,192.168.10.9,0,224.0.0.22,0,0,7/7/2017 9:00,54760,4,0,...,0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.0,BENIGN